# permissions for end users to edit aliyunstoreossbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: aliyunstoreossbinding-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: aliyun-ossbinding-operator
    app.kubernetes.io/part-of: aliyun-ossbinding-operator
    app.kubernetes.io/managed-by: kustomize
  name: aliyunstoreossbinding-editor-role
rules:
- apiGroups:
  - store.oss.binding.com.bailu
  resources:
  - aliyunstoreossbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - store.oss.binding.com.bailu
  resources:
  - aliyunstoreossbindings/status
  verbs:
  - get
