---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - store.oss.binding.com.bailu
  resources:
  - aliyunstoreossbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - store.oss.binding.com.bailu
  resources:
  - aliyunstoreossbindings/finalizers
  verbs:
  - update
- apiGroups:
  - store.oss.binding.com.bailu
  resources:
  - aliyunstoreossbindings/status
  verbs:
  - get
  - patch
  - update
